config/routes.rb
Ideas::Application.routes.draw do

  devise_for :users, path_names: { sign_in: "login", sign_out: "logout" },
                     controllers: { omniauth_callbacks: "omniauth_callbacks"}

  resources :ideas do
    resources :comments
    resources :attachments
    collection { post :import }
  end

  match 'archived', to: "ideas#archived", as: "archived"
  match 'savefile', to: "ideas#savefile", as: "savefile"  
  match 'import_form', to: "ideas#import_form", as: "import_form"  

  post "/ideas/:idea_id/votes/up" => "votes#up", as: "vote_up"
  post "/ideas/:idea_id/votes/down" => "votes#down", as: "vote_down"

  post "/ideas/:id/archive" => "ideas#archive", as: "archive"
  
  root to: "ideas#index"

end

app/models/idea.rb
class Idea < ActiveRecord::Base
  
  attr_accessible :title, :body, :user_id, :category, :archived_at, :attachments_attributes, :priority

  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :votes, dependent: :destroy
  has_many :attachments, dependent: :destroy
  accepts_nested_attributes_for :attachments, allow_destroy: true

  validates :title, presence: true
  validates :user_id, presence: true

  scope :by_latest, -> { order("updated_at desc") }
  scope :active, -> { where("archived_at IS NULL") }
  scope :archived, -> { where("archived_at IS NOT NULL") }
  scope :sort_by_count_votes_desc, -> do 
    select("ideas.*, COUNT(votes.id) as count_votes")
      .joins("LEFT OUTER JOIN votes ON ideas.id = votes.idea_id")
      .group("ideas.id").order("count_votes desc")
  end
  scope :sort_by_count_votes_asc, -> do
    select("ideas.*, COUNT(votes.id) as count_votes")
      .joins("LEFT OUTER JOIN votes ON ideas.id = votes.idea_id")
      .group("ideas.id").order("count_votes asc")
  end

  def archived?
    self.archived_at
  end

  def self.import(file, user)
    contents = []
    contents = CSV.read(file.path)
    contents.shift
    contents.each do |row|
      Idea.create(priority: row[0].to_i, title: row[1], body: row[2], user_id: user)
    end
  end

end

app/controllers/ideas_controller.rb
require 'csv'

class IdeasController < ApplicationController

  before_filter :authenticate_user!
  helper_method :resource

  def index
    @search = Idea.search(params[:search])
    @ideas = @search.page(params[:page]).active.by_latest
    @idea = Idea.new(params[:idea])
  end

  def archived
    @search = Idea.search(params[:search])
    @ideas = @search.page(params[:page]).archived.by_latest
  end

  def new
    @idea = Idea.new(params[:idea])
  end

  def show
    resource
  end

  def create
    idea = current_user.ideas.create(params[:idea])
    if idea.save
      redirect_to ideas_path, notice: "Idea added."
    else
      redirect_to :back, notice: "Unable to create new idea."
    end
  end

  def edit
    resource
  end

  def update
    if resource.update_attributes(params[:idea])
      redirect_to idea_path(resource), notice: "Idea updated."
    else
      redirect_to :back, notice: "Unable to update idea."
    end
  end

  def destroy
    resource.destroy
    redirect_to ideas_path, notice: "Idea deleted."
  end

  def archive
    resource.archived_at = DateTime.now
    if resource.save
      redirect_to ideas_path, notice: "Idea was archived."
    else
      redirect_to ideas_path, notice: "Could not archive."
    end
  end

  def savefile
    header = %w(Priority Title Body Category Up\ Vote Down\ Vote Author Date)
    @ideas = Idea.find(:all, order: 'created_at')
    doc = CSV.generate do |f| 
      f << header
      @ideas.each do |i|
        row = []
        row[0] = i.priority.to_i >= 0 ? i.priority : ""
        row << ActionView::Base.full_sanitizer.sanitize(i.title)
        row << ActionView::Base.full_sanitizer.sanitize(i.body.to_s.strip)
        row << i.category
        row << i.votes.up_vote.count
        row << i.votes.down_vote.count
        row << i.user.email
        row << i.created_at.strftime("%Y-%m-%d %H:%M")
        f << row
      end        
    end
    filename = "ideas_export"
    send_data doc, :type => 'text/csv; charset=iso-8859-1; header=present', :disposition => "attachment;filename=#{filename}.csv"
  end

  def import_form
  end

  def import
    Idea.import(params[:file], current_user.id)
    redirect_to ideas_path, notice: "Ideas imported from file."
  end

  private

  def resource
    @idea ||= Idea.find(params[:id])
  end

end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/views/ideas/_form.html.haml
= simple_form_for @idea do |f|
  = f.input :title, input_html: { class: "input-xxlarge idea_title_input" }, html: { multipart: true }
  = f.input :body, input_html: { :rows => 6, class: "input-xxlarge" }
  = f.input :category, collection: CATEGORIES, input_html: { class: "input-medium" }
  = f.input :priority, collection: PRIORITIES, input_html: { class: "input-mini" }
  .input.add_attachments
    = f.simple_fields_for :attachments do |builder|
      = render 'attachments/form', f: builder
    = link_to_add_fields "Add Image", f, :attachments
  %br
  = f.button :submit
  = link_to "Cancel", ideas_path, class: 'btn'

app/views/ideas/_idea.html.haml
.display_vote_counts
  = display_vote_counts(resource)
  %span{style: "padding-left: 8px"}Priority:
  = display_priority(resource)

%p
  %strong= full_title(resource)

%p= markdown resource.body.to_s

app/views/ideas/_quick_add.html.haml
= simple_form_for @idea do |f|
  = f.input :title, wrapper_html: { class: "input_wrapper" }, input_html: { style: "width: 510px" }
  = f.input :category, collection: CATEGORIES, input_html: { class: "input-medium" }, wrapper_html: { class: "input_wrapper" }
  = f.input :priority, collection: PRIORITIES, input_html: { class: "input-mini" }, wrapper_html: { class: "input_wrapper" }
  .input_wrapper
    = f.submit "Quick Add", class: "btn btn-primary", style: "margin-top: -10px"

app/views/ideas/_table.html.haml
%table.table.table-striped
  %thead
    %tr
      %th{ style: "width: 10%" }
        = sort_link @search, :count_votes, "Votes", :default_order => :desc
      %th{ style: "width: 10%" }
        = sort_link @search, :priority, "Priority", :default_order => :a
      %th{ style: "width: 45%" }
        = sort_link @search, :title, "Title"
      %th{ style: "width: 15%" }
        Author
      %th{ style: "width: 15%" }
        = sort_link @search, :updated_at, "Last Updated", :default_order => :desc
      %th{ style: "width: 5%" }
        
  %tbody
  - @ideas.each do |idea|
    %tr
      %td= display_vote_counts(idea)
      %td= display_priority(idea)
      %td
        = link_to full_title(idea), idea_path(idea)
        %br
        %small
          .idea_excerpt= markdown_excerpt excerpt(idea.body.to_s)
      %td
        %small= idea.user.email
      %td
        %small= distance_with_time(idea.updated_at, true)
      %td
        = archive_button(idea)

= paginate @ideas

app/views/ideas/archived.html.haml
%h3 Archived Ideas

= render "table"

app/views/ideas/edit.html.haml
%h3 Edit

= render "form"

app/views/ideas/import_form.html.haml
%h3 Import Ideas

%p Row format: Priority, Title, Body

= form_tag import_ideas_path, multipart: true do
  = file_field_tag :file
  = submit_tag "Import"

app/views/ideas/index.html.haml
%h3 Ideas Index

%ul.nav.nav-tabs
  %li#add_tab{style: "width: 50%; text-align: center;"}
    %a Quick Add
  %li#search_tab{style: "width: 50%; text-align: center;"} 
    %a Search
.well.well-small.page#add
  = render "quick_add"
.well.well-small.page#search
  = simple_form_for @search, defaults: { required: false } do |f|
    = f.input :title_or_body_contains, label: "Title/Desc", wrapper_html: { class: "input_wrapper" }, input_html: { style: "width: 373px" }
    = f.input :category_eq, label: "Category", collection: CATEGORIES, wrapper_html: { class: "input_wrapper" }, input_html: { class: "input-medium"}
    = f.input :user_email_contains, label: "Author", as: :string, wrapper_html: { class: "input_wrapper" }
    .input_wrapper
      = f.submit "Search", class: "btn btn-primary", style: "margin-top: -10px"

= render "table"

app/views/ideas/new.html.haml
%h3 New Idea

= render "form"

app/views/ideas/show.html.haml
%h3 Idea

.idea
  = render "ideas/idea"
  
  - unless resource.attachments.empty?
    %strong Attachments:
    %p
      - resource.attachments.each do |attachment|
        = image_link(attachment)

  %p
    %small= post_info(resource)

  %p.vote_buttons= display_voting(resource)

  %p
    - if owner?(resource)
      .user_options 
        = link_to "Edit", edit_idea_path(resource), class: "btn btn-primary btn-small"
        .btn-group.pull-right
          = archive_link(resource)
          = delete_link(resource)

= render partial: "comments/comments"