config/routes.rb
Ideas::Application.routes.draw do

  devise_for :users, path_names: { sign_in: "login", sign_out: "logout" },
                     controllers: { omniauth_callbacks: "omniauth_callbacks"}

  resources :ideas do
    resources :comments
    resources :attachments
    collection { post :import }
  end

  match 'archived', to: "ideas#archived", as: "archived"
  match 'savefile', to: "ideas#savefile", as: "savefile"  
  match 'import_form', to: "ideas#import_form", as: "import_form"  

  post "/ideas/:idea_id/votes/up" => "votes#up", as: "vote_up"
  post "/ideas/:idea_id/votes/down" => "votes#down", as: "vote_down"

  post "/ideas/:id/archive" => "ideas#archive", as: "archive"
  
  root to: "ideas#index"

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :body, :user_id, :idea_id

  belongs_to :idea
  belongs_to :user

  validates :body, presence: true
  validates :user_id, presence: true
  validates :idea_id, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  helper_method :resource
  
  def create
    idea = Idea.find(params[:idea_id])
    comment = idea.comments.build(params[:comment])
    comment.user_id = current_user.id
    if comment.save
      # Disabled mailing for now
      # UserMailer.delay.new_comment_notification(comment)
      render json: { success: true, comment: render_to_string(partial: "comments/comment", locals: { comment: comment }) }
    else
      render json: comment.errors.full_messages.join(', '), status: :unprocessable_entity
    end
  end

  def edit
    resource
  end

  def update
    if resource.update_attributes(params[:comment])
      redirect_to idea_path(resource.idea), notice: "Comment updated."
    else
      redirect_to idea_path(resource.idea), notice: "Unable to update comment."
    end
  end

  private

  def resource
    @comment ||= Comment.find(params[:id])
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.haml
.comment
  = markdown comment.body
  %p
    %small= post_info(comment)
    -if owner?(comment)
      /%p= link_to "Edit Comment", nil, class: 'btn btn-mini edit_comment', remote: true
      /%p= link_to_add_comments "comment", comment, :comments
      %p= link_to "Edit Comment", edit_idea_comment_path(comment.idea, comment), class: "btn btn-primary btn-mini"

app/views/comments/_comments.html.haml
.comments
  %h5 Comments

  .comments_list
    - resource.comments.each do |comment|
      = render partial: "comments/comment", locals: { comment: comment }

  .add_comment
    = render partial: "comments/form"

app/views/comments/_form.html.haml
= simple_form_for [@idea, Comment.new], remote: true do |f|
  = f.input :body, input_html: { :rows => 6, class: "input-xxlarge comment_body_input" }, label: false
  = f.button :submit, "Add Comment"

app/views/comments/edit.html.haml
%h3 Update Comment

.idea
  = render partial: "ideas/idea", locals: { resource: resource.idea }

  - unless resource.idea.attachments.empty?
    %strong Attachments:
    %p
      - resource.idea.attachments.each do |attachment|
        = image_thumbnail(attachment)

  %p
    %small= post_info(resource)

.comment
  = simple_form_for [resource.idea, resource] do |f|
    = f.input :body, input_html: { :rows => 6, class: "input-xxlarge comment_body_input" }, label: false
    = f.button :submit, "Update Comment"
    